# Generated by Django 4.1.1 on 2022-09-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=250)),
                ('disertante', models.CharField(max_length=100)),
                ('fecha_curso', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('precio', models.CharField(max_length=60)),
                ('dis_imagen', models.ImageField(upload_to='')),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
