# Generated by Django 4.1.1 on 2022-09-16 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_inscripciones_delete_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('payment_type', models.CharField(max_length=250)),
                ('order_id', models.CharField(max_length=250)),
                ('nombre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscripcion.inscripciones')),
            ],
        ),
    ]
